/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';
import { ComponentHostComponent, A2UI_SURFACE_ID } from './component-host.component';

/**
 * Lightweight component for rendering an A2UI child component.
 * Consumes metadata generated by the GenericBinder and injects context from the parent host.
 */
@Component({
  selector: 'a2ui-v09-child',
  imports: [ComponentHostComponent],
  template: `
    <a2ui-v09-component-host
      [componentId]="meta().id"
      [surfaceId]="surfaceId"
      [dataContextPath]="meta().basePath"
    ></a2ui-v09-component-host>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChildComponent {
  /** Metadata containing the component ID and its data model path. */
  meta = input.required<{ id: string; basePath: string }>();

  /** 
   * The Surface ID is provided by the root ComponentHost via Dependency Injection,
   * removing the need to pass it as an Input through every layer of the UI tree.
   */
  protected surfaceId = inject(A2UI_SURFACE_ID);
}
