# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerates the Express parser from the canonical ANTLR grammar.

The lexer, parser, and visitor in
``src/a2ui/inference_formats/experimental/express/generated/`` are generated from
``specification/inference_formats/express/Express.g4`` and committed. After
changing the grammar, run this from ``python/a2ui_agent`` and commit the result::

    uv run python scripts/generate_express_parser.py

With ``--check``, the script compares ``generated/`` with fresh output instead of
writing it, and exits 1 if they differ. CI runs this check.

ANTLR runs through ``antlr4-tools`` from the dev dependency group. It needs a
Java runtime (JRE 11 or newer) on the ``PATH`` and downloads the ANTLR jar on
first use.
"""

import argparse
import difflib
import os
import shutil
import subprocess
import sys
import sysconfig
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path

# Keep in step with the antlr4-python3-runtime pin in pyproject.toml.
ANTLR_VERSION = "4.13.2"

_SDK_DIR = Path(__file__).resolve().parents[1]
_GRAMMAR = (
    _SDK_DIR.parents[1]
    / "specification"
    / "inference_formats"
    / "express"
    / "Express.g4"
)
_GENERATED_DIR = (
    _SDK_DIR
    / "src"
    / "a2ui"
    / "inference_formats"
    / "experimental"
    / "express"
    / "generated"
)

# ANTLR names its output after the grammar; the package uses snake_case names.
_RENAMES = {
    "ExpressLexer.py": "express_lexer.py",
    "ExpressParser.py": "express_parser.py",
    "ExpressVisitor.py": "express_visitor.py",
    "ExpressLexer.tokens": "express_lexer.tokens",
    "Express.tokens": "express.tokens",
}
# The generated visitor imports the parser module under its original name.
_VISITOR = "express_visitor.py"
_IMPORT_REWRITES = {
    "from .ExpressParser import": "from .express_parser import",
    "from ExpressParser import": "from express_parser import",
}
_INIT = "__init__.py"
_INIT_CONTENT = b"# Generated by ANTLR. Do not edit manually.\n"

_REGENERATE_COMMAND = "uv run python scripts/generate_express_parser.py"
_MAX_DIFF_LINES_PER_FILE = 40


class GenerationError(Exception):
    """ANTLR could not be found or did not finish successfully."""


def _find_antlr() -> str:
    scripts_dir = sysconfig.get_path("scripts")
    antlr = shutil.which("antlr4", path=scripts_dir)
    if antlr is None:
        raise GenerationError(
            f"antlr4 was not found in {scripts_dir}. Run `uv sync` to install the"
            " dev dependency group, which provides antlr4-tools."
        )
    return antlr


def generate() -> dict[str, bytes]:
    """Runs ANTLR on the grammar and returns the files for ``generated/``.

    Returns:
        File contents keyed by their names in ``generated/``, after the
        snake_case renames and the visitor import rewrite.

    Raises:
        GenerationError: If the grammar or antlr4 is missing, or ANTLR fails.
    """
    if not _GRAMMAR.is_file():
        raise GenerationError(f"Grammar not found: {_GRAMMAR}")
    antlr = _find_antlr()
    env = dict(os.environ, ANTLR4_TOOLS_ANTLR_VERSION=ANTLR_VERSION)

    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp)
        # Running from the grammar's directory keeps absolute paths out of the
        # generated headers. With stdin closed, antlr4-tools fails at its
        # "install Java?" prompt instead of waiting for an answer.
        result = subprocess.run(
            [
                antlr,
                "-Dlanguage=Python3",
                "-visitor",
                "-no-listener",
                "-o",
                str(out_dir),
                _GRAMMAR.name,
            ],
            cwd=_GRAMMAR.parent,
            env=env,
            stdin=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode != 0:
            raise GenerationError(
                f"ANTLR failed with exit code {result.returncode}; see its output"
                " above. It needs a Java runtime (JRE 11 or newer) on the PATH."
            )
        files = {
            _RENAMES.get(path.name, path.name): path.read_bytes()
            for path in out_dir.iterdir()
            if path.is_file()
        }

    visitor = files[_VISITOR].decode("utf-8")
    for old, new in _IMPORT_REWRITES.items():
        visitor = visitor.replace(old, new)
    files[_VISITOR] = visitor.encode("utf-8")
    files[_INIT] = _INIT_CONTENT
    return files


def read_generated_dir() -> dict[str, bytes]:
    """Returns the files currently in ``generated/``, keyed by name."""
    if not _GENERATED_DIR.is_dir():
        return {}
    return {
        path.name: path.read_bytes()
        for path in _GENERATED_DIR.iterdir()
        if path.is_file()
    }


def stale_files(
    current: Mapping[str, bytes], expected: Mapping[str, bytes]
) -> list[str]:
    """Returns the names of files that are missing, extra, or different."""
    return sorted(
        name
        for name in current.keys() | expected.keys()
        if current.get(name) != expected.get(name)
    )


def _print_diff(
    name: str, current: Mapping[str, bytes], expected: Mapping[str, bytes]
) -> None:
    if name not in current:
        print(f"generated/{name}: missing")
        return
    if name not in expected:
        print(f"generated/{name}: not produced by ANTLR")
        return
    diff = list(
        difflib.unified_diff(
            current[name].decode("utf-8", "replace").splitlines(keepends=True),
            expected[name].decode("utf-8", "replace").splitlines(keepends=True),
            fromfile=f"generated/{name}",
            tofile=f"generated/{name} (from {_GRAMMAR.name})",
        )
    )
    for line in diff[:_MAX_DIFF_LINES_PER_FILE]:
        print(line, end="" if line.endswith("\n") else "\n")
    if len(diff) > _MAX_DIFF_LINES_PER_FILE:
        print(f"... {len(diff) - _MAX_DIFF_LINES_PER_FILE} more diff lines")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerates the Express parser from Express.g4."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "compare generated/ with fresh ANTLR output instead of writing it,"
            " and exit 1 if they differ"
        ),
    )
    args = parser.parse_args(argv)

    try:
        expected = generate()
    except GenerationError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    current = read_generated_dir()
    stale = stale_files(current, expected)
    location = _GENERATED_DIR.relative_to(_SDK_DIR).as_posix()

    if args.check:
        if not stale:
            print(f"{location} matches {_GRAMMAR.name}.")
            return 0
        for name in stale:
            _print_diff(name, current, expected)
        sys.stdout.flush()
        print(
            f"\n{location} is out of date ({', '.join(stale)}). Run"
            f" `{_REGENERATE_COMMAND}` from python/a2ui_agent and commit the"
            " result.",
            file=sys.stderr,
        )
        return 1

    _GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    # Delete before writing, so a name that differs only in case can't remove
    # a file that was just written on a case-insensitive filesystem.
    for name in stale:
        if name not in expected:
            (_GENERATED_DIR / name).unlink()
            print(f"deleted  {name}")
    for name in stale:
        if name in expected:
            (_GENERATED_DIR / name).write_bytes(expected[name])
            print(f"written  {name}")
    print(
        f"{location}: {len(stale)} file(s) updated."
        if stale
        else f"{location} is up to date."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
