name: Setup Flutter and Dart
description: Configures Java 17 and Flutter with caching
inputs:
  channel:
    description: Target Flutter channel
    default: "stable"
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "17"
        cache: "gradle"
    - uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs.channel }}
        cache: true
