/*
 * Generated by scripts/generate-interfaces.ts
 * DO NOT EDIT MANUALLY
 */

// Common Schemas from v0_9/schema/common-types
/** Generated from ComponentIdSchema */
export declare type ComponentId = string;

/** Generated from ChildListSchema */
export declare interface ChildList_0 {
    /** The unique identifier for a component. */
    componentId: ComponentId;
    /** The path to the list of component property objects in the data model. */
    path: string;
}
export declare type ChildList = ComponentId[] | ChildList_0;

/** Generated from DataBindingSchema */
export declare interface DataBinding {
    /** A JSON Pointer path to a value in the data model. */
    path: string;
}

/** Generated from DynamicValueSchema */
export declare type DynamicValue = string | number | boolean | any[] | DataBinding | FunctionCall;

/** Generated from DynamicStringSchema */
export declare type DynamicString = string | DataBinding | FunctionCall;

/** Generated from DynamicNumberSchema */
export declare type DynamicNumber = number | DataBinding | FunctionCall;

/** Generated from DynamicBooleanSchema */
export declare type DynamicBoolean = boolean | DataBinding | LogicExpression;

/** Generated from DynamicStringListSchema */
export declare type DynamicStringList = string[] | DataBinding | FunctionCall;

/** Generated from FunctionCallSchema */
export declare interface FunctionCall_Args {
    [x: string]: any;
}
export declare interface FunctionCall {
    /** The name of the function to call. */
    call: string;
    /** Arguments passed to the function. */
    args: FunctionCall_Args;
    returnType?: "string" | "number" | "boolean" | "array" | "object" | "any" | "void";
}

/** Generated from LogicExpressionSchema */
export declare interface LogicExpression_0 {
    and: LogicExpression[];
}
export declare interface LogicExpression_1 {
    or: LogicExpression[];
}
export declare interface LogicExpression_2 {
    not: LogicExpression;
}
export declare interface LogicExpression_3 {
    returnType?: "boolean" | undefined;
}
export declare interface LogicExpression_4 {
    true: true;
}
export declare interface LogicExpression_5 {
    false: false;
}
export declare type LogicExpression = LogicExpression_0 | LogicExpression_1 | LogicExpression_2 | (FunctionCall & LogicExpression_3) | LogicExpression_4 | LogicExpression_5;

/** Generated from CheckRuleSchema */
export declare interface CheckRule_0 {
    /** The error message to display if the check fails. */
    message: string;
}
export declare type CheckRule = LogicExpression & CheckRule_0;

/** Generated from CheckableSchema */
export declare interface Checkable {
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

/** Generated from ActionSchema */
export declare interface Action_Context {
    [x: string]: DynamicValue;
}
export declare interface Action_Event {
    name: string;
    context?: Action_Context | undefined;
}
export declare interface Action_0 {
    event: Action_Event;
}
export declare interface Action_1 {
    functionCall: FunctionCall;
}
export declare type Action = Action_0 | Action_1;

/** Generated from AccessibilityAttributesSchema */
export declare interface AccessibilityAttributes {
    /** REF:common_types.json#/$defs/DynamicString|A short string used by assistive technologies to convey the purpose of an element. */
    label?: DynamicString | undefined;
    /** REF:common_types.json#/$defs/DynamicString|Additional information provided by assistive technologies about an element. */
    description?: DynamicString | undefined;
}

/** Generated from AnyComponentSchema */
export declare interface AnyComponent {
    /** The type name of the component. */
    component: string;
    /** The unique identifier for a component. */
    id?: ComponentId | undefined;
    weight?: number | undefined;
}


// Server-to-Client Messages from v0_9/schema/server-to-client
/** Generated from CreateSurfaceMessageSchema */
export declare interface CreateSurfaceMessage_CreateSurface {
    /** The unique identifier for the UI surface to be rendered. */
    surfaceId: string;
    /** A string that uniquely identifies this catalog. */
    catalogId: string;
    /** Theme parameters for the surface. */
    theme?: any | undefined;
    /** If true, the client will send the full data model. */
    sendDataModel?: boolean | undefined;
}
export declare interface CreateSurfaceMessage {
    version: "v0.9";
    createSurface: CreateSurfaceMessage_CreateSurface;
}

/** Generated from UpdateComponentsMessageSchema */
export declare interface UpdateComponentsMessage_UpdateComponents {
    /** The unique identifier for the UI surface to be updated. */
    surfaceId: string;
    /** A list containing all UI components for the surface. */
    components: AnyComponent[];
}
export declare interface UpdateComponentsMessage {
    version: "v0.9";
    updateComponents: UpdateComponentsMessage_UpdateComponents;
}

/** Generated from UpdateDataModelMessageSchema */
export declare interface UpdateDataModelMessage_UpdateDataModel {
    /** The unique identifier for the UI surface this data model update applies to. */
    surfaceId: string;
    /** An optional path to a location within the data model. */
    path?: string | undefined;
    /** The data to be updated in the data model. */
    value?: any | undefined;
}
export declare interface UpdateDataModelMessage {
    version: "v0.9";
    updateDataModel: UpdateDataModelMessage_UpdateDataModel;
}

/** Generated from DeleteSurfaceMessageSchema */
export declare interface DeleteSurfaceMessage_DeleteSurface {
    /** The unique identifier for the UI surface to be deleted. */
    surfaceId: string;
}
export declare interface DeleteSurfaceMessage {
    version: "v0.9";
    deleteSurface: DeleteSurfaceMessage_DeleteSurface;
}


// Client-to-Server Messages from v0_9/schema/client-to-server
/** Generated from A2uiClientActionSchema */
export declare interface A2uiClientAction_Context {
    [x: string]: any;
}
export declare interface A2uiClientAction {
    /** The name of the action, taken from the component's action.event.name property. */
    name: string;
    /** The id of the surface where the event originated. */
    surfaceId: string;
    /** The id of the component that triggered the event. */
    sourceComponentId: string;
    /** An ISO 8601 timestamp of when the event occurred. */
    timestamp: string;
    /** A JSON object containing the key-value pairs from the component's action.event.context, after resolving all data bindings. */
    context: A2uiClientAction_Context;
}

/** Generated from A2uiValidationErrorSchema */
export declare interface A2uiValidationError {
    code: "VALIDATION_FAILED";
    /** The id of the surface where the error occurred. */
    surfaceId: string;
    /** The JSON pointer to the field that failed validation (e.g. '/components/0/text'). */
    path: string;
    /** A short one or two sentence description of why validation failed. */
    message: string;
}

/** Generated from A2uiGenericErrorSchema */
export declare interface A2uiGenericError {
    code: string;
    /** A short one or two sentence description of why the error occurred. */
    message: string;
    /** The id of the surface where the error occurred. */
    surfaceId: string;
}

/** Generated from A2uiClientMessageSchema */
export declare interface A2uiClientMessage_0 {
    version: "v0.9";
}
export declare interface A2uiClientMessage_Context {
    [x: string]: any;
}
export declare interface A2uiClientMessage_Action {
    /** The name of the action, taken from the component's action.event.name property. */
    name: string;
    /** The id of the surface where the event originated. */
    surfaceId: string;
    /** The id of the component that triggered the event. */
    sourceComponentId: string;
    /** An ISO 8601 timestamp of when the event occurred. */
    timestamp: string;
    /** A JSON object containing the key-value pairs from the component's action.event.context, after resolving all data bindings. */
    context: A2uiClientMessage_Context;
}
export declare interface A2uiClientMessage_1 {
    action: A2uiClientMessage_Action;
}
export declare interface A2uiClientMessage_Error {
    code: "VALIDATION_FAILED";
    /** The id of the surface where the error occurred. */
    surfaceId: string;
    /** The JSON pointer to the field that failed validation (e.g. '/components/0/text'). */
    path: string;
    /** A short one or two sentence description of why validation failed. */
    message: string;
}
export declare interface A2uiClientMessage_Error_2 {
    code: string;
    /** A short one or two sentence description of why the error occurred. */
    message: string;
    /** The id of the surface where the error occurred. */
    surfaceId: string;
}
export declare interface A2uiClientMessage_2 {
    error: A2uiClientMessage_Error | A2uiClientMessage_Error_2;
}
export declare type A2uiClientMessage = A2uiClientMessage_0 & (A2uiClientMessage_1 | A2uiClientMessage_2);

/** Generated from A2uiClientDataModelSchema */
export declare interface A2uiClientDataModel_0 {
}
export declare interface A2uiClientDataModel_Surfaces {
    [x: string]: A2uiClientDataModel_0;
}
export declare interface A2uiClientDataModel {
    version: "v0.9";
    /** A map of surface IDs to their current data models. */
    surfaces: A2uiClientDataModel_Surfaces;
}


// Basic Catalog Components from v0_9/basic_catalog/components/basic_components
/** Generated from TextSchema */
export declare interface Text {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The text content to display. While simple Markdown formatting is supported (i.e. without HTML, images, or links), utilizing dedicated UI components is generally preferred for a richer and more structured presentation. */
    text: string | DataBinding | FunctionCall;
    /** A hint for the base text style. */
    variant?: ("h1" | "h2" | "h3" | "h4" | "h5" | "caption" | "body") | undefined;
}

/** Generated from ImageSchema */
export declare interface Image {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The URL of the image to display. */
    url: string | DataBinding | FunctionCall;
    /** Specifies how the image should be resized to fit its container. This corresponds to the CSS 'object-fit' property. */
    fit?: ("contain" | "cover" | "fill" | "none" | "scaleDown") | undefined;
    /** A hint for the image size and style. */
    variant?: ("icon" | "avatar" | "smallFeature" | "mediumFeature" | "largeFeature" | "header") | undefined;
}

/** Generated from IconSchema */
export declare interface Icon_Name {
    path: string;
}
export declare interface Icon {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The name of the icon to display. */
    name: ("accountCircle" | "add" | "arrowBack" | "arrowForward" | "attachFile" | "calendarToday" | "call" | "camera" | "check" | "close" | "delete" | "download" | "edit" | "event" | "error" | "fastForward" | "favorite" | "favoriteOff" | "folder" | "help" | "home" | "info" | "locationOn" | "lock" | "lockOpen" | "mail" | "menu" | "moreVert" | "moreHoriz" | "notificationsOff" | "notifications" | "pause" | "payment" | "person" | "phone" | "photo" | "play" | "print" | "refresh" | "rewind" | "search" | "send" | "settings" | "share" | "shoppingCart" | "skipNext" | "skipPrevious" | "star" | "starHalf" | "starOff" | "stop" | "upload" | "visibility" | "visibilityOff" | "volumeDown" | "volumeMute" | "volumeOff" | "volumeUp" | "warning") | Icon_Name;
}

/** Generated from VideoSchema */
export declare interface Video {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The URL of the video to display. */
    url: string | DataBinding | FunctionCall;
}

/** Generated from AudioPlayerSchema */
export declare interface AudioPlayer {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The URL of the audio to be played. */
    url: string | DataBinding | FunctionCall;
    /** A description of the audio, such as a title or summary. */
    description?: (string | DataBinding | FunctionCall) | undefined;
}

/** Generated from RowSchema */
export declare interface Row_Children {
    /** The unique identifier for a component. */
    componentId: ComponentId;
    /** The path to the list of component property objects in the data model. */
    path: string;
}
export declare interface Row {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** Defines the children. Use an array of strings for a fixed set of children, or a template object to generate children from a data list. Children cannot be defined inline, they must be referred to by ID. */
    children: ComponentId[] | Row_Children;
    /** Defines the arrangement of children along the main axis (horizontally). Use 'spaceBetween' to push items to the edges, or 'start'/'end'/'center' to pack them together. */
    justify?: ("center" | "end" | "spaceAround" | "spaceBetween" | "spaceEvenly" | "start" | "stretch") | undefined;
    /** Defines the alignment of children along the cross axis (vertically). This is similar to the CSS 'align-items' property, but uses camelCase values (e.g., 'start'). */
    align?: ("start" | "center" | "end" | "stretch") | undefined;
}

/** Generated from ColumnSchema */
export declare interface Column_Children {
    /** The unique identifier for a component. */
    componentId: ComponentId;
    /** The path to the list of component property objects in the data model. */
    path: string;
}
export declare interface Column {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** Defines the children. Use an array of strings for a fixed set of children, or a template object to generate children from a data list. Children cannot be defined inline, they must be referred to by ID. */
    children: ComponentId[] | Column_Children;
    /** Defines the arrangement of children along the main axis (vertically). Use 'spaceBetween' to push items to the edges (e.g. header at top, footer at bottom), or 'start'/'end'/'center' to pack them together. */
    justify?: ("start" | "center" | "end" | "spaceBetween" | "spaceAround" | "spaceEvenly" | "stretch") | undefined;
    /** Defines the alignment of children along the cross axis (horizontally). This is similar to the CSS 'align-items' property. */
    align?: ("center" | "end" | "start" | "stretch") | undefined;
}

/** Generated from ListSchema */
export declare interface List_Children {
    /** The unique identifier for a component. */
    componentId: ComponentId;
    /** The path to the list of component property objects in the data model. */
    path: string;
}
export declare interface List {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** Defines the children. Use an array of strings for a fixed set of children, or a template object to generate children from a data list. */
    children: ComponentId[] | List_Children;
    /** The direction in which the list items are laid out. */
    direction?: ("vertical" | "horizontal") | undefined;
    /** Defines the alignment of children along the cross axis. */
    align?: ("start" | "center" | "end" | "stretch") | undefined;
}

/** Generated from CardSchema */
export declare interface Card {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The ID of the single child component to be rendered inside the card. To display multiple elements, you MUST wrap them in a layout component (like Column or Row) and pass that container's ID here. Do NOT pass multiple IDs or a non-existent ID. Do NOT define the child component inline. */
    child: string;
}

/** Generated from TabsSchema */
export declare interface Tabs_Tabs {
    /** The tab title. */
    title: string | DataBinding | FunctionCall;
    /** The ID of the child component. Do NOT define the component inline. */
    child: string;
}
export declare interface Tabs {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** An array of objects, where each object defines a tab with a title and a child component. */
    tabs: Tabs_Tabs[];
}

/** Generated from ModalSchema */
export declare interface Modal {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The ID of the component that opens the modal when interacted with (e.g., a button). Do NOT define the component inline. */
    trigger: string;
    /** The ID of the component to be displayed inside the modal. Do NOT define the component inline. */
    content: string;
}

/** Generated from DividerSchema */
export declare interface Divider {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The orientation of the divider. */
    axis?: ("horizontal" | "vertical") | undefined;
}

/** Generated from ButtonSchema */
export declare interface Button {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The ID of the child component. Use a 'Text' component for a labeled button. Only use an 'Icon' if the requirements explicitly ask for an icon-only button. Do NOT define the child component inline. */
    child: string;
    /** A hint for the button style. If omitted, a default button style is used. 'primary' indicates this is the main call-to-action button. 'borderless' means the button has no visual border or background, making its child content appear like a clickable link. */
    variant?: ("default" | "primary" | "borderless") | undefined;
    action: Action;
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

/** Generated from TextFieldSchema */
export declare interface TextField {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The text label for the input field. */
    label: string | DataBinding | FunctionCall;
    /** The value of the text field. */
    value?: (string | DataBinding | FunctionCall) | undefined;
    /** The type of input field to display. */
    variant?: ("longText" | "number" | "shortText" | "obscured") | undefined;
    /** A regular expression used for client-side validation of the input. */
    validationRegexp?: string | undefined;
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

/** Generated from CheckBoxSchema */
export declare interface CheckBox {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The text to display next to the checkbox. */
    label: string | DataBinding | FunctionCall;
    /** The current state of the checkbox (true for checked, false for unchecked). */
    value: boolean | DataBinding | LogicExpression;
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

/** Generated from ChoicePickerSchema */
export declare interface ChoicePicker_Options {
    /** The text to display for this option. */
    label: string | DataBinding | FunctionCall;
    /** The stable value associated with this option. */
    value: string;
}
export declare interface ChoicePicker {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The label for the group of options. */
    label?: (string | DataBinding | FunctionCall) | undefined;
    /** A hint for how the choice picker should be displayed and behave. */
    variant?: ("multipleSelection" | "mutuallyExclusive") | undefined;
    /** The list of available options to choose from. */
    options: ChoicePicker_Options[];
    /** The list of currently selected values. This should be bound to a string array in the data model. */
    value: string[] | DataBinding | FunctionCall;
    /** The display style of the component. */
    displayStyle?: ("checkbox" | "chips") | undefined;
    /** If true, displays a search input to filter the options. */
    filterable?: boolean | undefined;
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

/** Generated from SliderSchema */
export declare interface Slider {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The label for the slider. */
    label?: (string | DataBinding | FunctionCall) | undefined;
    /** The minimum value of the slider. */
    min?: number | undefined;
    /** The maximum value of the slider. */
    max: number;
    /** The current value of the slider. */
    value: number | DataBinding | FunctionCall;
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

/** Generated from DateTimeInputSchema */
export declare interface DateTimeInput {
    /** REF:common_types.json#/$defs/AccessibilityAttributes|Attributes to enhance accessibility. */
    accessibility?: AccessibilityAttributes | undefined;
    /** The relative weight of this component within a Row or Column. This is similar to the CSS 'flex-grow' property. Note: this may ONLY be set when the component is a direct descendant of a Row or Column. */
    weight?: number | undefined;
    /** The selected date and/or time value in ISO 8601 format. If not yet set, initialize with an empty string. */
    value: string | DataBinding | FunctionCall;
    /** If true, allows the user to select a date. */
    enableDate?: boolean | undefined;
    /** If true, allows the user to select a time. */
    enableTime?: boolean | undefined;
    /** The minimum allowed date/time in ISO 8601 format. */
    min?: (DynamicString | string | string | string) | undefined;
    /** The maximum allowed date/time in ISO 8601 format. */
    max?: (DynamicString | string | string | string) | undefined;
    /** The text label for the input field. */
    label?: (string | DataBinding | FunctionCall) | undefined;
    /** A list of checks to perform. */
    checks?: CheckRule[] | undefined;
}

