import { zodToTs, printNode, withGetType } from "zod-to-ts";
import { z } from "zod";
import * as fs from "fs";
import * as path from "path";
import ts from "typescript";

// Import schemas using dynamic imports with tsx
async function generate() {
  const root = process.cwd();
  const versions = ["v0_8", "v0_9"];

  for (const v of versions) {
    console.log(`Generating interfaces for ${v}...`);
    const outputDir = path.join(root, "src", v, "schema");
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
    const outputPath = path.join(outputDir, "common-interfaces.ts");
    
    let content = `/*\n * Generated by scripts/generate-interfaces.ts\n * DO NOT EDIT MANUALLY\n */\n\n`;
    
    // 1. Load mappings from schemas.ts
    const schemasPath = path.join(root, "src", v, "schema", "schemas.ts");
    if (fs.existsSync(schemasPath)) {
        console.log(`  Importing ${v}/schema/schemas.ts...`);
        const module = await import(schemasPath);
        
        // Common Schemas
        const CommonSchemas = module.CommonSchemas;
        if (CommonSchemas) {
            console.log(`    Found ${Object.keys(CommonSchemas).length} common schemas.`);
            
            // Register external references
            for (const [name, schema] of Object.entries(CommonSchemas)) {
                if (schema) {
                    withGetType(schema as any, (ts) => ts.factory.createIdentifier(name));
                }
            }

            content += `// Common Schemas from ${v}/schema/common-types\n`;
            for (const [name, schema] of Object.entries(CommonSchemas)) {
                if (!schema) {
                    console.warn(`    Schema ${name} is undefined!`);
                    continue;
                }
                
                // Temporarily remove the getType override for the current schema
                // so that generateInterface can see its internal structure
                // instead of just its own name.
                const schemaAny = schema as any;
                const originalGetType = schemaAny._def.getType;
                delete schemaAny._def.getType;

                content += generateInterface(schema as any, name);

                // Restore it for subsequent calls that might reference this schema
                schemaAny._def.getType = originalGetType;
            }
        }

        // 2. Messaging & Catalog Schemas (v0_9 only)
        if (v === "v0_9") {
            const ServerToClientMessageSchemas = module.ServerToClientMessageSchemas;
            if (ServerToClientMessageSchemas) {
                console.log(`    Found ${Object.keys(ServerToClientMessageSchemas).length} server-to-client schemas.`);
                content += `\n// Server-to-Client Messages from v0_9/schema/server-to-client\n`;
                for (const [name, schema] of Object.entries(ServerToClientMessageSchemas)) {
                    content += generateInterface(schema as any, name);
                }
            }

            const ClientToServerMessageSchemas = module.ClientToServerMessageSchemas;
            if (ClientToServerMessageSchemas) {
                console.log(`    Found ${Object.keys(ClientToServerMessageSchemas).length} client-to-server schemas.`);
                content += `\n// Client-to-Server Messages from v0_9/schema/client-to-server\n`;
                for (const [name, schema] of Object.entries(ClientToServerMessageSchemas)) {
                    content += generateInterface(schema as any, name);
                }
            }

            const BASIC_COMPONENTS = module.BASIC_COMPONENTS;
            if (BASIC_COMPONENTS) {
                console.log(`    Found ${BASIC_COMPONENTS.length} basic catalog components.`);
                content += `\n// Basic Catalog Components from v0_9/basic_catalog/components/basic_components\n`;
                for (const comp of BASIC_COMPONENTS) {
                    content += generateInterface(comp.schema, comp.name);
                }
            }
        }
    } else {
        console.warn(`    schemas.ts NOT FOUND for ${v}.`);
    }

    fs.writeFileSync(outputPath, content);
    console.log(`  Wrote ${outputPath}`);
  }
}

function toPascalCase(s: string): string {
  return s
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

function generateInterface(schema: any, name: string): string {
  try {
    let effectiveSchema = schema;
    if (schema instanceof z.ZodLazy) {
        effectiveSchema = (schema as any)._def.getter();
    }
    const { node } = zodToTs(effectiveSchema, name, { resolveRecursive: true });
    
    const auxiliaryNodes: ts.InterfaceDeclaration[] = [];
    const usedNames = new Set<string>();
    let objectCount = 0;

    const modifiers = [
        ts.factory.createModifier(ts.SyntaxKind.ExportKeyword),
        ts.factory.createModifier(ts.SyntaxKind.DeclareKeyword)
    ];

    const transform = (typeNode: ts.Node, nameHint?: string): ts.Node => {
        if (ts.isTypeLiteralNode(typeNode)) {
            let auxNameSuggestion = nameHint ? `${name}_${toPascalCase(nameHint)}` : `${name}_${objectCount++}`;
            let auxName = auxNameSuggestion;
            
            // Handle name collisions
            let count = 2;
            if (usedNames.has(auxName)) {
                // If it's a generic name like Checkbox_0, we don't want to double up the counter if possible
                // but for simplicity we'll just append.
                while (usedNames.has(`${auxNameSuggestion}_${count}`)) {
                    count++;
                }
                auxName = `${auxNameSuggestion}_${count}`;
            }
            usedNames.add(auxName);

            const auxInterface = ts.factory.createInterfaceDeclaration(
                modifiers,
                auxName,
                undefined,
                undefined,
                typeNode.members.map(member => transform(member) as ts.TypeElement)
            );
            auxiliaryNodes.push(auxInterface);
            return ts.factory.createTypeReferenceNode(auxName, undefined);
        }

        if (ts.isPropertySignature(typeNode)) {
            let propName = "";
            if (ts.isIdentifier(typeNode.name)) {
                propName = typeNode.name.text;
            } else if (ts.isStringLiteral(typeNode.name)) {
                propName = typeNode.name.text;
            }
            return ts.factory.updatePropertySignature(
                typeNode,
                typeNode.modifiers,
                typeNode.name,
                typeNode.questionToken,
                typeNode.type ? (transform(typeNode.type, propName) as ts.TypeNode) : undefined
            );
        }

        if (ts.isUnionTypeNode(typeNode)) {
            const types = typeNode.types
                .map(t => transform(t, nameHint) as ts.TypeNode)
                .filter(t => {
                    if (ts.isTypeReferenceNode(t) && ts.isIdentifier(t.typeName) && t.typeName.text === name) {
                        return false;
                    }
                    return true;
                });
            if (types.length === 0) return ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword);
            if (types.length === 1) return types[0];
            return ts.factory.createUnionTypeNode(types);
        }
        if (ts.isIntersectionTypeNode(typeNode)) {
            const types = typeNode.types
                .map(t => transform(t, nameHint) as ts.TypeNode)
                .filter(t => {
                    if (ts.isTypeReferenceNode(t) && ts.isIdentifier(t.typeName) && t.typeName.text === name) {
                        return false;
                    }
                    return true;
                });
            if (types.length === 0) return ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword);
            if (types.length === 1) return types[0];
            return ts.factory.createIntersectionTypeNode(types);
        }
        if (ts.isArrayTypeNode(typeNode)) {
            return ts.factory.createArrayTypeNode(transform(typeNode.elementType, nameHint) as ts.TypeNode);
        }
        if (ts.isParenthesizedTypeNode(typeNode)) {
            return ts.factory.createParenthesizedType(transform(typeNode.type, nameHint) as ts.TypeNode);
        }

        return ts.visitEachChild(typeNode, (child) => transform(child), undefined as any);
    };

    let mainDeclaration: ts.Node;
    if (ts.isTypeLiteralNode(node)) {
        mainDeclaration = ts.factory.createInterfaceDeclaration(
            modifiers,
            name,
            undefined,
            undefined,
            node.members.map(member => transform(member) as ts.TypeElement)
        );
    } else {
        mainDeclaration = ts.factory.createTypeAliasDeclaration(
            modifiers,
            name,
            undefined,
            transform(node) as ts.TypeNode
        );
    }

    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
    const sourceFile = ts.createSourceFile("temp.ts", "", ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);
    
    let result = `/** Generated from ${name}Schema */\n`;
    for (const aux of auxiliaryNodes) {
        result += printer.printNode(ts.EmitHint.Unspecified, aux, sourceFile) + "\n";
    }
    result += printer.printNode(ts.EmitHint.Unspecified, mainDeclaration, sourceFile) + "\n\n";

    return result;
  } catch (e) {
    console.warn(`  Failed to generate interface for ${name}:`, e);
    return `// Failed to generate interface for ${name}\n\n`;
  }
}

generate().catch(console.error);
