// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Copies the published basic catalog documents into Dart source, so
/// `BasicCatalog` reads its component schemas from the specification rather
/// than from a hand-written copy.
///
/// Run from the package directory after editing a published catalog:
///
/// ```sh
/// dart run tool/generate_basic_catalogs.dart
/// ```
///
/// `test/basic_catalog_test.dart` fails if the checked-in output has drifted
/// from the published documents.
library;

import 'dart:io';

/// A published catalog document and the Dart library that embeds it.
typedef BasicCatalogSource = ({
  String source,
  String output,
  String constant,
  String version,
});

/// The documents to copy, relative to the repository root, and the files to
/// write, relative to the package directory.
const List<BasicCatalogSource> sources = [
  (
    source: 'specification/v0_9/catalogs/basic/catalog.json',
    output: 'lib/src/basic_catalog/v0_9/catalog.g.dart',
    constant: 'basicCatalogV0_9Json',
    version: 'v0.9',
  ),
  (
    source: 'catalogs/basic/v1/catalog.json',
    output: 'lib/src/basic_catalog/v1_0/catalog.g.dart',
    constant: 'basicCatalogV1_0Json',
    version: 'v1.0',
  ),
];

void main() {
  for (final BasicCatalogSource entry in sources) {
    final String json = readSource(entry.source);
    File(entry.output).writeAsStringSync(render(entry, json));
    stdout.writeln('Wrote ${entry.output} from ${entry.source}.');
  }
}

/// Reads [source], searching upwards for the repository root so the tool runs
/// from the package directory or the workspace root.
String readSource(String source) {
  Directory dir = Directory.current;
  while (true) {
    final candidate = File('${dir.path}/$source');
    if (candidate.existsSync()) return candidate.readAsStringSync();
    final Directory parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError(
        'Could not find $source above ${Directory.current.path}.',
      );
    }
    dir = parent;
  }
}

/// Wraps [json] in a Dart library, verbatim, so the generated file diffs
/// against the published document one line at a time.
///
/// The document is embedded as a raw multiline string, which reproduces `$`
/// and `\` without escaping. Throws if [json] is not expressible that way, so
/// an edit to the document cannot silently produce a file that says something
/// other than what it copied.
String render(BasicCatalogSource entry, String json) {
  final String source = entry.source;
  if (json.contains("'''")) {
    throw StateError("$source contains ''', which ends the string literal.");
  }
  if (json.endsWith("'")) {
    throw StateError("$source ends with ', which extends the delimiter.");
  }
  if (!json.startsWith('{')) {
    throw StateError('$source does not start with a JSON object.');
  }
  return '''
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by tool/generate_basic_catalogs.dart. Do not edit by hand.
//
// A verbatim copy of $source.

/// The basic catalog document for protocol ${entry.version}, as published.
const String ${entry.constant} = r\'\'\'
$json\'\'\';
''';
}
