/*
 * Generated by scripts/generate-interfaces.ts
 * DO NOT EDIT MANUALLY
 */

// Common Schemas from v0_8/schema/common-types
/** Generated from StringValueSchema */
export declare interface StringValue {
    path?: string | undefined;
    literalString?: string | undefined;
    literal?: string | undefined;
}

/** Generated from DataValueSchema */
export declare interface DataValue {
    key: string;
    valueString?: string | undefined;
    valueNumber?: number | undefined;
    valueBoolean?: boolean | undefined;
    valueMap?: DataValue[] | undefined;
}

/** Generated from NumberValueSchema */
export declare interface NumberValue {
    path?: string | undefined;
    literalNumber?: number | undefined;
    literal?: number | undefined;
}

/** Generated from BooleanValueSchema */
export declare interface BooleanValue {
    path?: string | undefined;
    literalBoolean?: boolean | undefined;
    literal?: boolean | undefined;
}

/** Generated from ActionSchema */
export declare interface Action_Value {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    /** A fixed, hardcoded string value. */
    literalString?: string | undefined;
    literalNumber?: number | undefined;
    literalBoolean?: boolean | undefined;
}
export declare interface Action_Context {
    key: string;
    value: Action_Value;
}
export declare interface Action {
    /** A unique name identifying the action (e.g., 'submitForm'). */
    name: string;
    /** A key-value map of data bindings to be resolved when the action is triggered. */
    context?: Action_Context[] | undefined;
}

/** Generated from TextSchema */
export declare interface Text {
    text: StringValue;
    usageHint?: ("h1" | "h2" | "h3" | "h4" | "h5" | "caption" | "body") | undefined;
}

/** Generated from ImageSchema */
export declare interface Image {
    url: StringValue;
    usageHint?: ("icon" | "avatar" | "smallFeature" | "mediumFeature" | "largeFeature" | "header") | undefined;
    fit?: ("contain" | "cover" | "fill" | "none" | "scale-down") | undefined;
    altText?: StringValue | undefined;
}

/** Generated from IconSchema */
export declare interface Icon {
    name: StringValue;
}

/** Generated from VideoSchema */
export declare interface Video {
    url: StringValue;
}

/** Generated from AudioPlayerSchema */
export declare interface AudioPlayer {
    url: StringValue;
    /** A label, title, or placeholder text. */
    description?: StringValue | undefined;
}

/** Generated from TabsSchema */
export declare interface Tabs_Title {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    /** A fixed, hardcoded string value. */
    literalString?: string | undefined;
}
export declare interface Tabs_TabItems {
    title: Tabs_Title;
    /** A reference to a component instance by its unique ID. */
    child: string;
}
export declare interface Tabs {
    /** A list of tabs, each with a title and a child component ID. */
    tabItems: Tabs_TabItems[];
}

/** Generated from DividerSchema */
export declare interface Divider {
    /** The orientation. */
    axis?: ("horizontal" | "vertical") | undefined;
    /** The color of the divider (e.g., hex code or semantic name). */
    color?: string | undefined;
    /** The thickness of the divider. */
    thickness?: number | undefined;
}

/** Generated from ModalSchema */
export declare interface Modal {
    /** The ID of the component (e.g., a button) that triggers the modal. */
    entryPointChild: string;
    /** The ID of the component to display as the modal's content. */
    contentChild: string;
}

/** Generated from ButtonSchema */
export declare interface Button_Value {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    /** A fixed, hardcoded string value. */
    literalString?: string | undefined;
    literalNumber?: number | undefined;
    literalBoolean?: boolean | undefined;
}
export declare interface Button_Context {
    key: string;
    value: Button_Value;
}
export declare interface Button_Action {
    /** A unique name identifying the action (e.g., 'submitForm'). */
    name: string;
    /** A key-value map of data bindings to be resolved when the action is triggered. */
    context?: Button_Context[] | undefined;
}
export declare interface Button {
    /** The ID of the component to display as the button's content. */
    child: string;
    /** Represents a user-initiated action. */
    action: Button_Action;
    /** Indicates if this button should be styled as the primary action. */
    primary?: boolean | undefined;
}

/** Generated from CheckboxSchema */
export declare interface Checkbox_Value {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    literalBoolean?: boolean | undefined;
}
export declare interface Checkbox {
    label: StringValue;
    value: Checkbox_Value;
}

/** Generated from TextFieldSchema */
export declare interface TextField_Label {
    path?: string | undefined;
    literalString?: string | undefined;
    literal?: string | undefined;
}
export declare interface TextField {
    text?: StringValue | undefined;
    /** A label, title, or placeholder text. */
    label: TextField_Label;
    textFieldType?: ("shortText" | "number" | "date" | "longText") | undefined;
    /** A regex string to validate the input. */
    validationRegexp?: string | undefined;
}

/** Generated from DateTimeInputSchema */
export declare interface DateTimeInput {
    value: StringValue;
    enableDate?: boolean | undefined;
    enableTime?: boolean | undefined;
    /** The string format for the output (e.g., 'YYYY-MM-DD'). */
    outputFormat?: string | undefined;
}

/** Generated from MultipleChoiceSchema */
export declare interface MultipleChoice_Selections {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    literalArray?: string[] | undefined;
}
export declare interface MultipleChoice_Label {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    /** A fixed, hardcoded string value. */
    literalString?: string | undefined;
}
export declare interface MultipleChoice_Options {
    label: MultipleChoice_Label;
    value: string;
}
export declare interface MultipleChoice {
    selections: MultipleChoice_Selections;
    options?: MultipleChoice_Options[] | undefined;
    maxAllowedSelections?: number | undefined;
    type?: ("checkbox" | "chips") | undefined;
    filterable?: boolean | undefined;
}

/** Generated from SliderSchema */
export declare interface Slider_Value {
    /** A data binding reference to a location in the data model (e.g., '/user/name'). */
    path?: string | undefined;
    literalNumber?: number | undefined;
}
export declare interface Slider {
    value: Slider_Value;
    minValue?: number | undefined;
    maxValue?: number | undefined;
}

/** Generated from ComponentArrayTemplateSchema */
export declare interface ComponentArrayTemplate {
    componentId: string;
    dataBinding: string;
}

/** Generated from ComponentArrayReferenceSchema */
export declare interface ComponentArrayReference_Template {
    componentId: string;
    dataBinding: string;
}
export declare interface ComponentArrayReference {
    explicitList?: string[] | undefined;
    /** A template for generating a dynamic list of children from a data model list. `componentId` is the component to use as a template, and `dataBinding` is the path to the map of components in the data model. Values in the map will define the list of children. */
    template?: ComponentArrayReference_Template | undefined;
}

/** Generated from RowSchema */
export declare interface Row {
    children: ComponentArrayReference;
    distribution?: ("start" | "center" | "end" | "spaceBetween" | "spaceAround" | "spaceEvenly") | undefined;
    alignment?: ("start" | "center" | "end" | "stretch") | undefined;
}

/** Generated from ColumnSchema */
export declare interface Column {
    children: ComponentArrayReference;
    distribution?: ("start" | "center" | "end" | "spaceBetween" | "spaceAround" | "spaceEvenly") | undefined;
    alignment?: ("start" | "center" | "end" | "stretch") | undefined;
}

/** Generated from ListSchema */
export declare interface List {
    children: ComponentArrayReference;
    direction?: ("vertical" | "horizontal") | undefined;
    alignment?: ("start" | "center" | "end" | "stretch") | undefined;
}

/** Generated from CardSchema */
export declare interface Card {
    /** The ID of the component to be rendered inside the card. */
    child: string;
}

