import {
  StringValueSchema,
  DataValueSchema,
  NumberValueSchema,
  BooleanValueSchema,
  ActionSchema,
  TextSchema,
  ImageSchema,
  IconSchema,
  VideoSchema,
  AudioPlayerSchema,
  TabsSchema,
  DividerSchema,
  ModalSchema,
  ButtonSchema,
  CheckboxSchema,
  TextFieldSchema,
  DateTimeInputSchema,
  MultipleChoiceSchema,
  SliderSchema,
  ComponentArrayTemplateSchema,
  ComponentArrayReferenceSchema,
  RowSchema,
  ColumnSchema,
  ListSchema,
  CardSchema,
} from "./common-types.js";

export const CommonSchemas = {
  StringValue: StringValueSchema,
  DataValue: DataValueSchema,
  NumberValue: NumberValueSchema,
  BooleanValue: BooleanValueSchema,
  Action: ActionSchema,
  Text: TextSchema,
  Image: ImageSchema,
  Icon: IconSchema,
  Video: VideoSchema,
  AudioPlayer: AudioPlayerSchema,
  Tabs: TabsSchema,
  Divider: DividerSchema,
  Modal: ModalSchema,
  Button: ButtonSchema,
  Checkbox: CheckboxSchema,
  TextField: TextFieldSchema,
  DateTimeInput: DateTimeInputSchema,
  MultipleChoice: MultipleChoiceSchema,
  Slider: SliderSchema,
  ComponentArrayTemplate: ComponentArrayTemplateSchema,
  ComponentArrayReference: ComponentArrayReferenceSchema,
  Row: RowSchema,
  Column: ColumnSchema,
  List: ListSchema,
  Card: CardSchema,
};
